name: CI/CD for Terraform and Ansible

on:
  push:
    branches:
      - main

jobs:
  terraform-ansible:
    name: Terraform Plan & Apply and Ansible
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
        cli_config_credentials_token: ${{ secrets.YC_TOKEN }}

    # Initialize Terraform
    - name: Initialize Terraform
      run: terraform -chdir=terraform init

    # Terraform Plan
    - name: Terraform Plan
      run: terraform -chdir=terraform plan -var-file=variables.tf

    # Terraform Apply
    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve -var-file=variables.tf

    # Remove known_hosts entry for the server
    - name: Clean known_hosts entry
      run: |
        ssh-keygen -R $(terraform -chdir=terraform output -raw vm_public_ip)

    # Disable host key checking
    - name: Disable SSH host key checking
      run: echo "export ANSIBLE_HOST_KEY_CHECKING=False" >> $GITHUB_ENV

    # Install Ansible
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    # Run Ansible playbook
    - name: Run Ansible Playbook
      run: |
        ansible-playbook ansible/playbook.yml -i ansible/inventory.ini



